allowBuilds:
  '@parcel/watcher': true
  '@swc/core': true
  cypress: true
  esbuild: true
  less: true
  lmdb: true
  msgpackr-extract: true
  nx: true
  protobufjs: true
overrides:
  '@babel/plugin-transform-modules-systemjs@>=7.12.0 <=7.29.3': '>=7.29.4'
  axios@>=1.0.0 <1.15.1: '>=1.15.1'
  axios@>=1.0.0 <1.15.2: '>=1.15.2'
  brace-expansion@>=4.0.0 <5.0.5: '>=5.0.5'
  follow-redirects@<=1.15.11: '>=1.16.0'
  ip-address@<=10.1.0: '>=10.1.1'
  picomatch@>=4.0.0 <4.0.4: '>=4.0.4'
  undici@>=7.0.0 <7.24.0: '>=7.24.0'
  undici@>=7.17.0 <7.24.0: '>=7.24.0'
  yaml@>=2.0.0 <2.8.3: '>=2.8.3'
