allowBuilds:
  '@google/genai': false
  '@parcel/watcher': true
  '@swc/core': true
  cypress: true
  esbuild: true
  less: true
  lmdb: true
  msgpackr-extract: true
  nx: true
  protobufjs: true
minimumReleaseAgeExclude:
  - ws@8.20.1 || 8.21.0
  - '@angular/platform-server@21.2.13 || 21.2.15 || 21.2.16'
  - uuid@11.1.1
  - qs@6.15.2
  - hono@4.12.21 || 4.12.25
  - shell-quote@1.8.4
  - tmp@0.2.6
  - esbuild@0.28.1
  - '@angular/core@21.2.15 || 21.2.17'
  - '@angular/common@21.2.15 || 21.2.17'
  - protobufjs@7.6.1 || 7.6.3
  - form-data@4.0.6
  - '@angular/compiler@21.2.15 || 21.2.17'
  - tar@7.5.16
  - vite@7.3.5 || 8.0.16
  - launch-editor@2.14.1
  - js-yaml@4.1.2
  - '@babel/core@7.29.1'
  - webpack-dev-server@5.2.5
  - http-proxy-middleware@2.0.10 || 3.0.6 || 3.0.7
  - piscina@5.1.5
  - undici@7.28.0
